# Generated by Django 4.2.7 on 2026-04-06 06:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReorderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_stock_level', models.PositiveIntegerField()),
                ('current_stock_snapshot', models.IntegerField()),
                ('requested_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('exhausted', 'Exhausted Suppliers'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reorder_requests', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReorderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField()),
                ('requested_quantity', models.PositiveIntegerField()),
                ('fulfilled_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('partial', 'Partial'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('email_failed', 'Email Failed')], default='pending', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reorder_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_requests', to='products.autoreorderrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_requests', to='products.supplier')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplierPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_priorities', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_priorities', to='products.supplier')),
            ],
            options={
                'ordering': ['product_id', 'priority', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productsupplierpriority',
            constraint=models.UniqueConstraint(fields=('product', 'supplier'), name='uniq_product_supplier'),
        ),
        migrations.AddConstraint(
            model_name='productsupplierpriority',
            constraint=models.UniqueConstraint(fields=('product', 'priority'), name='uniq_product_supplier_priority'),
        ),
    ]
