# Generated by Django 4.2.7 on 2026-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_autoreorderrequest_supplierreorderrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
