# Generated by Django 4.2.7 on 2026-04-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_max_stock_product_pack_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
