# Generated by Django 4.2.7 on 2026-04-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierreorderrequest',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
