# Generated by Django 4.2.7 on 2026-04-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_supplierreorderrequest_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='priority',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.DeleteModel(
            name='ProductSupplierPriority',
        ),
    ]
