# Generated by Django 4.2.7 on 2026-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_supplier_priority_delete_productsupplierpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreorderrequest',
            name='branch_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
