# Generated by Django 4.2.7 on 2026-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_autoreorderrequest_branch_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierreorderrequest',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
