# Generated by Django 4.2.7 on 2026-04-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_supplierreorderrequest_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreorderrequest',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
    ]
