# Generated by Django 4.2.7 on 2026-04-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_autoreorderrequest_admin_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoreorderrequest",
            name="origin",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                default="auto",
                max_length=12,
            ),
        ),
    ]
