# Generated by Django 4.2.7 on 2026-08-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_clear_zero_stock_auto_exemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exempt_from_auto_reorder',
            field=models.BooleanField(default=False, help_text='Set automatically by the auto-reorder scan when this product is in stock (quantity > 0) and has not sold at this branch for at least the configured stale period.'),
        ),
    ]
