# Generated by Django 4.2.7 on 2026-09-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0022_alter_stock_exempt_from_auto_reorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierreorderrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_reorder_requests', to='branches.branch'),
        ),
    ]
